// NOTA: Questo file è usato come fallback di emergenza quando il backend non è raggiungibile.
// La fonte primaria dei dati è il DB (PostgreSQL via Spring Boot) con URL Cloudinary (oe1bztwb).

export const galleryItems = [
  {
    "id": "d2081e46-807f-4013-aa67-e5cec03c1ec1",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263096/vinco_eventi_galleria/pzddkpcmlyqbsljns8ro.mp4",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263096/vinco_eventi_galleria/pzddkpcmlyqbsljns8ro.jpg",
    "titleIta": "Live Show Voce Internazionale Black",
    "titleEng": "Live Show International Black Voice",
    "subtitleIta": "L'energia unica della grande musica internazionale.",
    "subtitleEng": "The unique energy of great international music.",
    "category": "live",
    "featured": true,
    "startTime": 0,
    "displayOrder": 1
  },
  {
    "id": "a94264ce-4bdd-47a4-b41b-22120dc471a2",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263122/vinco_eventi_galleria/szrl81itjz5jlmqpugs8.mov",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263122/vinco_eventi_galleria/szrl81itjz5jlmqpugs8.jpg",
    "titleIta": "Set ELETTRICO - Promo on Fire!",
    "titleEng": "ELECTRICAL Set - Promo on Fire!",
    "subtitleIta": "La carica travolgente del nostro set elettrico live",
    "subtitleEng": "The overwhelming energy of our live electric set",
    "category": "djset",
    "featured": true,
    "startTime": 60,
    "displayOrder": 1
  },
  {
    "id": "1bca78ef-e6c6-4285-98e6-9b989c3d91f2",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263607/vinco_eventi_galleria/elk7c1i2fhbicxppaio3.mov",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263607/vinco_eventi_galleria/elk7c1i2fhbicxppaio3.jpg",
    "titleIta": "Trolling Band Live Performance",
    "titleEng": "Trolling Band Live Performance",
    "subtitleIta": "Spettacolo musicale d'impatto e ritmo coinvolgente",
    "subtitleEng": "High impact musical performance with engaging rhythm",
    "category": "band",
    "featured": true,
    "startTime": null,
    "displayOrder": 2
  },
  {
    "id": "9ea48442-9008-4b27-bc8b-70d31d5c0c44",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263234/vinco_eventi_galleria/uyo7bds1jo7ztj5dvxrt.mp4",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263234/vinco_eventi_galleria/uyo7bds1jo7ztj5dvxrt.jpg",
    "titleIta": "DJ Set Exclusive Live",
    "titleEng": "DJ Set Exclusive Live",
    "subtitleIta": "Carica ed energia per eventi unici",
    "subtitleEng": "Energy and passion for unique events",
    "category": "djset",
    "featured": false,
    "startTime": null,
    "displayOrder": 3
  },
  {
    "id": "85df4170-f0c2-4bae-8fda-774edede2bf7",
    "type": "image",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263251/vinco_eventi_galleria/bidvwp7jodwszfkxqosr.jpg",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263251/vinco_eventi_galleria/bidvwp7jodwszfkxqosr.jpg",
    "titleIta": "Console DJ Set",
    "titleEng": "Console DJ Set",
    "subtitleIta": "Musica e regia per la serata",
    "subtitleEng": "Music and direction for your evening",
    "category": "djset",
    "featured": false,
    "startTime": null,
    "displayOrder": 4
  },
  {
    "id": "738176f5-6252-4a14-abe5-0a86c900c22d",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263617/vinco_eventi_galleria/rh4ohem59vp7tjurpxjl.mov",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263617/vinco_eventi_galleria/rh4ohem59vp7tjurpxjl.jpg",
    "titleIta": "Exclusive Night Party",
    "titleEng": "Exclusive Night Party",
    "subtitleIta": "Pista piena e grande energia per una serata indimenticabile",
    "subtitleEng": "Packed dancefloor and intense energy for an unforgettable night",
    "category": "djset",
    "featured": true,
    "startTime": null,
    "displayOrder": 5
  },
  {
    "id": "7f29e574-f99a-4090-861b-c91bf754f336",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263627/vinco_eventi_galleria/qeo3dwrage0zrrxl8ewp.mp4",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263627/vinco_eventi_galleria/qeo3dwrage0zrrxl8ewp.jpg",
    "titleIta": "Live Band Night Performance",
    "titleEng": "Live Band Night Performance",
    "subtitleIta": "Spettacolo e musica dal vivo",
    "subtitleEng": "Live show and music performance",
    "category": "band",
    "featured": true,
    "startTime": null,
    "displayOrder": 6
  },
  {
    "id": "be0d8b55-7727-4176-a3dd-783dcdee674d",
    "type": "image",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263314/vinco_eventi_galleria/rof3imwpuhwbr5apypuj.jpg",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263314/vinco_eventi_galleria/rof3imwpuhwbr5apypuj.jpg",
    "titleIta": "Esibizione Vocalist & Cantante",
    "titleEng": "Vocalist & Singer Performance",
    "subtitleIta": "Emozione pura durante il party",
    "subtitleEng": "Pure emotion during the party",
    "category": "band",
    "featured": false,
    "startTime": null,
    "displayOrder": 7
  },
  {
    "id": "1321e1d7-4b8a-4d7a-b969-4bc352eb80f5",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263318/vinco_eventi_galleria/q7zrwzqmlrqmtcuktr6s.mp4",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263318/vinco_eventi_galleria/q7zrwzqmlrqmtcuktr6s.jpg",
    "titleIta": "Luci LED & Console Show",
    "titleEng": "LED Lights & Console Show",
    "subtitleIta": "Scenografie luminose e sound system",
    "subtitleEng": "Lighting design and sound system",
    "category": "lightshow",
    "featured": false,
    "startTime": null,
    "displayOrder": 8
  },
  {
    "id": "5dcf4d5b-75aa-449e-bab5-153ea9c55a34",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263641/vinco_eventi_galleria/wiijhyqiocdt5cdx5y2l.mov",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263641/vinco_eventi_galleria/wiijhyqiocdt5cdx5y2l.jpg",
    "titleIta": "Live Energy & Dj Set",
    "titleEng": "Live Energy & Dj Set",
    "subtitleIta": "Intrattenimento e regia musicale sul palco",
    "subtitleEng": "Entertainment and musical direction on stage",
    "category": "live",
    "featured": false,
    "startTime": null,
    "displayOrder": 9
  },
  {
    "id": "233b39d0-1edb-4b2f-836b-674bc1294f0c",
    "type": "image",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263331/vinco_eventi_galleria/v8ks87iku9tngw1bruew.jpg",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263331/vinco_eventi_galleria/v8ks87iku9tngw1bruew.jpg",
    "titleIta": "Illuminazione Cielo Stellato",
    "titleEng": "Starry Sky Lighting",
    "subtitleIta": "Atmosfera magica per la cena all'aperto",
    "subtitleEng": "Magical atmosphere for outdoor dinner",
    "category": "decor",
    "featured": false,
    "startTime": null,
    "displayOrder": 10
  },
  {
    "id": "e5a53a1e-fbfe-4fce-838a-2d76ba0c47fc",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263654/vinco_eventi_galleria/ex1mgxm2uy5lz6qgdv8e.mov",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263654/vinco_eventi_galleria/ex1mgxm2uy5lz6qgdv8e.jpg",
    "titleIta": "Wedding Party Highlights",
    "titleEng": "Wedding Party Highlights",
    "subtitleIta": "I momenti più belli ed emozionanti del party",
    "subtitleEng": "The best and most exciting moments of the party",
    "category": "wedding",
    "featured": true,
    "startTime": null,
    "displayOrder": 11
  },
  {
    "id": "2b9b7c2a-a8bb-4667-ba0b-2fb335865e2d",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263335/vinco_eventi_galleria/eqqreymgmqf5gqlwfw4j.mp4",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263335/vinco_eventi_galleria/eqqreymgmqf5gqlwfw4j.jpg",
    "titleIta": "Party & Clubbing Vibe",
    "titleEng": "Party & Clubbing Vibe",
    "subtitleIta": "Pista piena e divertimento assicurato",
    "subtitleEng": "Full dancefloor and guaranteed fun",
    "category": "djset",
    "featured": false,
    "startTime": null,
    "displayOrder": 12
  },
  {
    "id": "7f4e6e2c-e9c9-4a92-827d-cff62fc2819d",
    "type": "image",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263353/vinco_eventi_galleria/eslngwueqhugdpg8hi7f.jpg",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263353/vinco_eventi_galleria/eslngwueqhugdpg8hi7f.jpg",
    "titleIta": "Il Primo Bacio degli Sposi",
    "titleEng": "The Bride & Groom First Kiss",
    "subtitleIta": "Momento romantico accompagnato dalla musica",
    "subtitleEng": "Romantic moment accompanied by music",
    "category": "wedding",
    "featured": false,
    "startTime": null,
    "displayOrder": 13
  },
  {
    "id": "60c67e73-1b60-4126-a66e-688cfe2e381d",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263355/vinco_eventi_galleria/qtzhhcmopjmllnfq5v1c.mov",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263355/vinco_eventi_galleria/qtzhhcmopjmllnfq5v1c.jpg",
    "titleIta": "Live Vibes & Social Reel",
    "titleEng": "Live Vibes & Social Reel",
    "subtitleIta": "La magia dell'evento vista da vicino",
    "subtitleEng": "The magic of the event up close",
    "category": "live",
    "featured": true,
    "startTime": null,
    "displayOrder": 14
  },
  {
    "id": "4bd803bc-7069-42a7-87f6-d937ef88c56a",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263380/vinco_eventi_galleria/txyarfrqwfgi9vnncizj.mp4",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263380/vinco_eventi_galleria/txyarfrqwfgi9vnncizj.jpg",
    "titleIta": "Live Acoustics Aperitivo",
    "titleEng": "Live Acoustics Cocktail Hour",
    "subtitleIta": "Musica dal vivo elegante durante il cocktail",
    "subtitleEng": "Elegant live music during cocktail hour",
    "category": "band",
    "featured": false,
    "startTime": null,
    "displayOrder": 15
  },
  {
    "id": "96f04bd3-ede7-4e7f-b1b8-502106aaf699",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263390/vinco_eventi_galleria/d5s1wklgzgtbq46szfqw.mov",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263390/vinco_eventi_galleria/d5s1wklgzgtbq46szfqw.jpg",
    "titleIta": "Atmosphere & Lights",
    "titleEng": "Atmosphere & Lights",
    "subtitleIta": "Service luci ed effetti per un'atmosfera elegante",
    "subtitleEng": "Lighting and effects service for an elegant atmosphere",
    "category": "lightshow",
    "featured": false,
    "startTime": null,
    "displayOrder": 16
  },
  {
    "id": "87574b9b-15a7-4b05-a4db-6314f62b3a71",
    "type": "image",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263415/vinco_eventi_galleria/rtrdezuxotxduilwgri3.jpg",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263415/vinco_eventi_galleria/rtrdezuxotxduilwgri3.jpg",
    "titleIta": "Brindisi & Taglio Torta",
    "titleEng": "Toast & Cake Cutting",
    "subtitleIta": "Il culmine dei festeggiamenti",
    "subtitleEng": "The climax of the celebrations",
    "category": "wedding",
    "featured": false,
    "startTime": null,
    "displayOrder": 17
  },
  {
    "id": "3beaf748-4d77-4710-aa52-3a76b0669385",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263417/vinco_eventi_galleria/noqx9sae1ohhkc1pxrq1.mp4",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263417/vinco_eventi_galleria/noqx9sae1ohhkc1pxrq1.jpg",
    "titleIta": "Fumogeni & Effetti Scenografici",
    "titleEng": "Smoke Effects & Special Effects",
    "subtitleIta": "Effetti speciali per ingressi e momenti clou",
    "subtitleEng": "Special effects for grand entrances and key moments",
    "category": "effects",
    "featured": false,
    "startTime": null,
    "displayOrder": 18
  },
  {
    "id": "b4d8dc39-f64c-4f42-9922-50f311cd3b9f",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263425/vinco_eventi_galleria/kdnqwlqmyegmhinbm8hu.mov",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263425/vinco_eventi_galleria/kdnqwlqmyegmhinbm8hu.jpg",
    "titleIta": "Festeggiamenti in Musica",
    "titleEng": "Music Celebrations",
    "subtitleIta": "Ritmo e divertimento scatenato per gli invitati",
    "subtitleEng": "Rhythm and wild fun for the guests",
    "category": "djset",
    "featured": false,
    "startTime": null,
    "displayOrder": 19
  },
  {
    "id": "aded5d5d-0512-45c4-b6ba-d719811f3c68",
    "type": "image",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263468/vinco_eventi_galleria/ktpkgfadh3dnnpyltcmv.jpg",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263468/vinco_eventi_galleria/ktpkgfadh3dnnpyltcmv.jpg",
    "titleIta": "Fumogeni Colorati Sposi",
    "titleEng": "Colored Smoke Effects",
    "subtitleIta": "Esplosione di colori per un ricordo indimenticabile",
    "subtitleEng": "Burst of colors for an unforgettable memory",
    "category": "effects",
    "featured": true,
    "startTime": null,
    "displayOrder": 20
  },
  {
    "id": "2699052c-1bce-4e3c-9567-419240ade6b4",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263473/vinco_eventi_galleria/to262rl7hltav0td4pxe.mp4",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263473/vinco_eventi_galleria/to262rl7hltav0td4pxe.jpg",
    "titleIta": "DJ Set & Live Mix",
    "titleEng": "DJ Set & Live Mix",
    "subtitleIta": "Selezione musicale personalizzata",
    "subtitleEng": "Customized music selection",
    "category": "djset",
    "featured": false,
    "startTime": null,
    "displayOrder": 21
  },
  {
    "id": "9882feea-50a0-42c7-a544-4c3328f4bb7e",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263484/vinco_eventi_galleria/wg9vj1u26m0dppyvaolc.mov",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263484/vinco_eventi_galleria/wg9vj1u26m0dppyvaolc.jpg",
    "titleIta": "Live Show Console",
    "titleEng": "Live Show Console",
    "subtitleIta": "Performance ed energia con la regia di Vinco Eventi",
    "subtitleEng": "Performance and energy directed by Vinco Eventi",
    "category": "djset",
    "featured": true,
    "startTime": null,
    "displayOrder": 22
  },
  {
    "id": "3ddcd687-d701-414b-a15d-508d44264ed8",
    "type": "image",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263520/vinco_eventi_galleria/lhblxjk1gjjevfjlagdj.jpg",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263520/vinco_eventi_galleria/lhblxjk1gjjevfjlagdj.jpg",
    "titleIta": "Band Live Aperitivo",
    "titleEng": "Live Band Cocktail Hour",
    "subtitleIta": "Ritmi lounge e pop acustico",
    "subtitleEng": "Lounge rhythms and acoustic pop",
    "category": "band",
    "featured": false,
    "startTime": null,
    "displayOrder": 23
  },
  {
    "id": "719d9028-fce7-492f-af8b-71e85028588e",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263522/vinco_eventi_galleria/pcdebon0rjwc06lvjiq9.mov",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263522/vinco_eventi_galleria/pcdebon0rjwc06lvjiq9.jpg",
    "titleIta": "DJ Set Moment",
    "titleEng": "DJ Set Moment",
    "subtitleIta": "Sound system e selezione musicale d'eccellenza",
    "subtitleEng": "Sound system and music selection of excellence",
    "category": "djset",
    "featured": true,
    "startTime": null,
    "displayOrder": 24
  },
  {
    "id": "3fbc227f-4679-407a-b9d1-55b861c3a374",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263531/vinco_eventi_galleria/ungksxqaytblfum0pik0.mp4",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263531/vinco_eventi_galleria/ungksxqaytblfum0pik0.jpg",
    "titleIta": "Live Show Finale",
    "titleEng": "Live Show Finale",
    "subtitleIta": "Gran finale con la band al completo",
    "subtitleEng": "Grand finale with full band",
    "category": "band",
    "featured": false,
    "startTime": null,
    "displayOrder": 25
  },
  {
    "id": "c718cb6c-3d8a-4ed1-a2c2-124f3f3ba3c5",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263543/vinco_eventi_galleria/zgzyugwbgruplplndoqz.mov",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263543/vinco_eventi_galleria/zgzyugwbgruplplndoqz.jpg",
    "titleIta": "Show dal Vivo",
    "titleEng": "Live Performance Show",
    "subtitleIta": "Coinvolgimento e spettacolo per tutti gli ospiti",
    "subtitleEng": "Engagement and show for all guests",
    "category": "live",
    "featured": false,
    "startTime": null,
    "displayOrder": 26
  },
  {
    "id": "5305f9b7-d471-4c00-b115-17b494916735",
    "type": "image",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263556/vinco_eventi_galleria/x7f3skkjpxn4pwjppjug.jpg",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263556/vinco_eventi_galleria/x7f3skkjpxn4pwjppjug.jpg",
    "titleIta": "Cocktail & Sax Vibe",
    "titleEng": "Cocktail & Sax Vibe",
    "subtitleIta": "Eleganza e sonorità moderne",
    "subtitleEng": "Elegance and modern sounds",
    "category": "band",
    "featured": true,
    "startTime": null,
    "displayOrder": 27
  },
  {
    "id": "363126b4-d0ac-4432-8341-753bf974b0c7",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263558/vinco_eventi_galleria/nvpyujwgsgr8lk2ckzmh.mov",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263558/vinco_eventi_galleria/nvpyujwgsgr8lk2ckzmh.jpg",
    "titleIta": "Live Session Highlight",
    "titleEng": "Live Session Highlight",
    "subtitleIta": "Un assaggio del nostro intrattenimento dal vivo",
    "subtitleEng": "A taste of our live entertainment",
    "category": "band",
    "featured": false,
    "startTime": null,
    "displayOrder": 28
  },
  {
    "id": "3e8f613c-360e-4a00-8832-99c14ad816a6",
    "type": "image",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263565/vinco_eventi_galleria/gsbm8iddkpawzho0zfgm.png",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263565/vinco_eventi_galleria/gsbm8iddkpawzho0zfgm.png",
    "titleIta": "I Nostri Musicisti",
    "titleEng": "Our Musicians",
    "subtitleIta": "Professionisti al servizio del tuo evento",
    "subtitleEng": "Professionals at the service of your event",
    "category": "band",
    "featured": false,
    "startTime": null,
    "displayOrder": 29
  },
  {
    "id": "5166c260-3a07-4c61-8f41-78c3c044f1bd",
    "type": "video",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/video/upload/v1786263570/vinco_eventi_galleria/nwlnzyc8lvea9uqeox48.mov",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/video/upload/f_jpg,q_auto,w_720,so_2/v1786263570/vinco_eventi_galleria/nwlnzyc8lvea9uqeox48.jpg",
    "titleIta": "Live Sound Experience",
    "titleEng": "Live Sound Experience",
    "subtitleIta": "Musica e passione al servizio del tuo evento",
    "subtitleEng": "Music and passion at the service of your event",
    "category": "band",
    "featured": false,
    "startTime": null,
    "displayOrder": 30
  },
  {
    "id": "187ee2ad-2832-418e-a096-b5e22d1a762e",
    "type": "image",
    "isFallback": true,
    "src": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263576/vinco_eventi_galleria/prdvzblf1ekne41jybur.jpg",
    "posterUrl": "https://res.cloudinary.com/oe1bztwb/image/upload/v1786263576/vinco_eventi_galleria/prdvzblf1ekne41jybur.jpg",
    "titleIta": "Accoglienza Ospiti in Musica",
    "titleEng": "Guest Welcome in Music",
    "subtitleIta": "L'atmosfera ideale fin dai primi minuti",
    "subtitleEng": "The ideal atmosphere from the very first minutes",
    "category": "band",
    "featured": true,
    "startTime": null,
    "displayOrder": 31
  }
];
