// NOTA: File di fallback offline/emergenza sincronizzato con Cloudinary (fzdamrbc).
// La fonte primaria dei dati dinamici è il DB PostgreSQL su Neon / Render.

export const galleryItems = [
  {
    "displayOrder": 1,
    "type": "video",
    "titleIta": "Showreel Presentazione Ufficiale",
    "titleEng": "Official Presentation Showreel",
    "subtitleIta": "L'eccellenza, l'energia e le emozioni firmate VINCO EVENTI.",
    "subtitleEng": "The excellence, energy and emotions signed by VINCO EVENTI.",
    "category": "live",
    "featured": true,
    "startTime": 0,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903295/vinco_eventi_galleria/vinco_eventi_galleria/Video_presentazione_vinco_eventi_.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903295/vinco_eventi_galleria/vinco_eventi_galleria/Video_presentazione_vinco_eventi_.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/Video_presentazione_vinco_eventi_",
    "id": "dde69263-f5b6-40a1-aee9-f3257f132ce3",
    "isFallback": true
  },
  {
    "displayOrder": 2,
    "type": "video",
    "titleIta": "Black Voice & Live Sax su Dancefloor 3D",
    "titleEng": "Black Voice & Live Sax on 3D Dancefloor",
    "subtitleIta": "Uno spettacolo esclusivo con voce black internazionale, sax live e pista LED 3D.",
    "subtitleEng": "An exclusive show with international black vocals, live sax and 3D LED dancefloor.",
    "category": "djset",
    "featured": true,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903300/vinco_eventi_galleria/vinco_eventi_galleria/blasck_voice___sax_on_dancefloor_3d.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903300/vinco_eventi_galleria/vinco_eventi_galleria/blasck_voice___sax_on_dancefloor_3d.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/blasck_voice___sax_on_dancefloor_3d",
    "id": "f44b086a-9278-4938-b17f-cae346dc325f",
    "isFallback": true
  },
  {
    "displayOrder": 3,
    "type": "video",
    "titleIta": "Live Show Duo Violino Scenografico",
    "titleEng": "Scenic Violin Duo Live Show",
    "subtitleIta": "Performance vibrante con violini scenografici ed effetti visivi mozzafiato.",
    "subtitleEng": "Vibrant performance with scenic violins and breathtaking visual effects.",
    "category": "live",
    "featured": true,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903303/vinco_eventi_galleria/vinco_eventi_galleria/live_show_duo_violino.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903303/vinco_eventi_galleria/vinco_eventi_galleria/live_show_duo_violino.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/live_show_duo_violino",
    "id": "0970c218-5a40-4de9-8f1a-dff4d3f05934",
    "isFallback": true
  },
  {
    "displayOrder": 4,
    "type": "video",
    "titleIta": "DJ Vincenzo Colaluca & Live Percussion Show",
    "titleEng": "DJ Vincenzo Colaluca & Live Percussion Show",
    "subtitleIta": "Ritmo travolgente e percussioni dal vivo sulla dancefloor.",
    "subtitleEng": "Overwhelming rhythm and live percussions on the dancefloor.",
    "category": "djset",
    "featured": true,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903310/vinco_eventi_galleria/vinco_eventi_galleria/dj_colaluca_djset___percussion.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903310/vinco_eventi_galleria/vinco_eventi_galleria/dj_colaluca_djset___percussion.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/dj_colaluca_djset___percussion",
    "id": "83139e51-3794-4b46-bd47-cf3015e94ca3",
    "isFallback": true
  },
  {
    "displayOrder": 5,
    "type": "video",
    "titleIta": "Live Band & Party Explosion",
    "titleEng": "Live Band & Party Explosion",
    "subtitleIta": "Energia pura e grandi successi suonati dal vivo per far ballare tutti gli ospiti.",
    "subtitleEng": "Pure energy and live hits to keep all guests dancing.",
    "category": "band",
    "featured": true,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903316/vinco_eventi_galleria/vinco_eventi_galleria/live_band_2.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903316/vinco_eventi_galleria/vinco_eventi_galleria/live_band_2.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/live_band_2",
    "id": "c342c0d1-15a8-4186-a524-b64d417a6f53",
    "isFallback": true
  },
  {
    "displayOrder": 6,
    "type": "video",
    "titleIta": "American Destination Wedding DJ Set",
    "titleEng": "American Destination Wedding DJ Set",
    "subtitleIta": "Soundtrack internazionale per matrimoni ed eventi esclusivi in Puglia.",
    "subtitleEng": "International soundtrack for luxury destination weddings in Puglia.",
    "category": "djset",
    "featured": true,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903322/vinco_eventi_galleria/vinco_eventi_galleria/dj_set_colaluca_american_wedding.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903322/vinco_eventi_galleria/vinco_eventi_galleria/dj_set_colaluca_american_wedding.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/dj_set_colaluca_american_wedding",
    "id": "76b4c5b6-80cc-4e98-a19c-574b0347b055",
    "isFallback": true
  },
  {
    "displayOrder": 7,
    "type": "video",
    "titleIta": "Arpa & Violino Romantic Ceremony",
    "titleEng": "Arpa & Violino Romantic Ceremony",
    "subtitleIta": "Atmosfere raffinate ed eleganti per il rito civile o religioso.",
    "subtitleEng": "Refined and elegant atmospheres for civil or religious ceremonies.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903325/vinco_eventi_galleria/vinco_eventi_galleria/arpa___violino.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903325/vinco_eventi_galleria/vinco_eventi_galleria/arpa___violino.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/arpa___violino",
    "id": "03089eef-5edb-4c80-9d11-d6ea5289ed7a",
    "isFallback": true
  },
  {
    "displayOrder": 8,
    "type": "video",
    "titleIta": "Chitarra Live & Loop Station Acoustic",
    "titleEng": "Live Guitar & Acoustic Loop Station",
    "subtitleIta": "Sonorità acustiche moderne e coinvolgenti per l'aperitivo.",
    "subtitleEng": "Modern acoustic grooves and loop acoustic vibes for welcome drinks.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903338/vinco_eventi_galleria/vinco_eventi_galleria/chitarra_live.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903338/vinco_eventi_galleria/vinco_eventi_galleria/chitarra_live.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/chitarra_live",
    "id": "d90278cf-ccfe-4899-94b2-740cf70ec92f",
    "isFallback": true
  },
  {
    "displayOrder": 9,
    "type": "video",
    "titleIta": "Dancefloor 3D Infinity Mirror Effect",
    "titleEng": "3D Infinity Mirror LED Dancefloor",
    "subtitleIta": "Pista da ballo LED 3D per un party futuristico e spettacolare.",
    "subtitleEng": "3D LED dancefloor for a futuristic and breathtaking party experience.",
    "category": "lightshow",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903341/vinco_eventi_galleria/vinco_eventi_galleria/dancefloor_3d.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903341/vinco_eventi_galleria/vinco_eventi_galleria/dancefloor_3d.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/dancefloor_3d",
    "id": "7f27ba31-c451-4fde-abc2-b56197882af2",
    "isFallback": true
  },
  {
    "displayOrder": 10,
    "type": "video",
    "titleIta": "DJ Set & Sax Afterparty",
    "titleEng": "DJ Set & Sax Afterparty",
    "subtitleIta": "Il mix perfetto tra beat elettronici e improvvisazione sax dal vivo.",
    "subtitleEng": "The perfect blend of electronic beats and live sax improvisation.",
    "category": "djset",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903345/vinco_eventi_galleria/vinco_eventi_galleria/dj_set___sax_afterparty.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903345/vinco_eventi_galleria/vinco_eventi_galleria/dj_set___sax_afterparty.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/dj_set___sax_afterparty",
    "id": "ad27aef6-4ca5-4c14-8e7f-0f5287f17056",
    "isFallback": true
  },
  {
    "displayOrder": 11,
    "type": "video",
    "titleIta": "Borgo Ritella Destination Wedding Party",
    "titleEng": "Borgo Ritella Destination Wedding Party",
    "subtitleIta": "Serata indimenticabile in una delle location più suggestive di Puglia.",
    "subtitleEng": "Unforgettable party night in one of Puglia's most prestigious venues.",
    "category": "djset",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903348/vinco_eventi_galleria/vinco_eventi_galleria/djset_borgo_ritella_destination_wedding.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903348/vinco_eventi_galleria/vinco_eventi_galleria/djset_borgo_ritella_destination_wedding.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/djset_borgo_ritella_destination_wedding",
    "id": "259f0e39-4f42-4955-89a6-2813351b6e20",
    "isFallback": true
  },
  {
    "displayOrder": 12,
    "type": "video",
    "titleIta": "VINCO EVENTI Crew DJ Set",
    "titleEng": "VINCO EVENTI Crew DJ Set",
    "subtitleIta": "La professionalità e la sintonia del nostro team artistico.",
    "subtitleEng": "The harmony, passion and expertise of our artistic DJ crew.",
    "category": "djset",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903352/vinco_eventi_galleria/vinco_eventi_galleria/djset_vinco_eventi_team.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903352/vinco_eventi_galleria/vinco_eventi_galleria/djset_vinco_eventi_team.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/djset_vinco_eventi_team",
    "id": "d085b48d-652b-41fb-bfd8-c4368d620bba",
    "isFallback": true
  },
  {
    "displayOrder": 13,
    "type": "video",
    "titleIta": "Duo Voce & One Man Band",
    "titleEng": "Vocals Duo & One Man Band",
    "subtitleIta": "Intrattenimento versatile e polistrumentale per ogni momento del ricevimento.",
    "subtitleEng": "Versatile multi-instrumental performance tailored for every reception phase.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903355/vinco_eventi_galleria/vinco_eventi_galleria/duo_voce_e_onemanband.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903355/vinco_eventi_galleria/vinco_eventi_galleria/duo_voce_e_onemanband.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/duo_voce_e_onemanband",
    "id": "753eddfa-a3f7-4cd0-8147-c6a165518478",
    "isFallback": true
  },
  {
    "displayOrder": 14,
    "type": "video",
    "titleIta": "Live Band Wedding Performance",
    "titleEng": "Live Band Wedding Performance",
    "subtitleIta": "Repertorio pop, rock e dance suonato con passione e maestria.",
    "subtitleEng": "Pop, rock and dance repertoire performed live with style and mastery.",
    "category": "band",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903360/vinco_eventi_galleria/vinco_eventi_galleria/live_band.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903360/vinco_eventi_galleria/vinco_eventi_galleria/live_band.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/live_band",
    "id": "5ab48f9d-987e-43cd-bb5f-aaf8b165adfc",
    "isFallback": true
  },
  {
    "displayOrder": 15,
    "type": "video",
    "titleIta": "International Black Voice Live",
    "titleEng": "International Black Voice Live",
    "subtitleIta": "Timbro soul e potenza vocale per un'esperienza da brividi.",
    "subtitleEng": "Soulful power vocals delivering chills and pure musical passion.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903365/vinco_eventi_galleria/vinco_eventi_galleria/live_black_voice.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903365/vinco_eventi_galleria/vinco_eventi_galleria/live_black_voice.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/live_black_voice",
    "id": "c88d73f3-83a9-47e3-aa12-9e9f781485da",
    "isFallback": true
  },
  {
    "displayOrder": 16,
    "type": "video",
    "titleIta": "Quartetto d'Archi Candlelight Emotion",
    "titleEng": "Candlelight String Quartet Emotion",
    "subtitleIta": "La magia degli archi a lume di candela per momenti indimenticabili.",
    "subtitleEng": "Candlelight string enchantment for unforgettable emotional highlights.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903368/vinco_eventi_galleria/vinco_eventi_galleria/quartetto_archi_candle.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903368/vinco_eventi_galleria/vinco_eventi_galleria/quartetto_archi_candle.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/quartetto_archi_candle",
    "id": "f89d4972-263e-441e-9317-9711cbb4489f",
    "isFallback": true
  },
  {
    "displayOrder": 17,
    "type": "video",
    "titleIta": "Female Saxophone Solo Performance",
    "titleEng": "Female Saxophone Solo Performance",
    "subtitleIta": "Eleganza, fascino e note calde per l'accoglienza degli ospiti.",
    "subtitleEng": "Elegance, charm and warm melodies welcoming your guests.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903370/vinco_eventi_galleria/vinco_eventi_galleria/sax_donna.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903370/vinco_eventi_galleria/vinco_eventi_galleria/sax_donna.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/sax_donna",
    "id": "802f9016-9172-4cc1-9c75-83dace988ed8",
    "isFallback": true
  },
  {
    "displayOrder": 18,
    "type": "video",
    "titleIta": "Live Saxophone & Full Band Jam",
    "titleEng": "Live Saxophone & Full Band Jam",
    "subtitleIta": "Armonia e virtuosismo con il sax solista integrato nella band.",
    "subtitleEng": "Harmony and virtuosic solos with live sax integrated with the band.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903376/vinco_eventi_galleria/vinco_eventi_galleria/sax_live_with_band.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903376/vinco_eventi_galleria/vinco_eventi_galleria/sax_live_with_band.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/sax_live_with_band",
    "id": "685f32d9-c1d2-4eef-bb4f-0207b83e3ee0",
    "isFallback": true
  },
  {
    "displayOrder": 19,
    "type": "video",
    "titleIta": "Service AV Vintage Discoball Scenografico",
    "titleEng": "Scenic Vintage Discoball AV Setup",
    "subtitleIta": "Riflessi di luce scintillanti per un'atmosfera retrò ed elegante.",
    "subtitleEng": "Glittering light reflections creating an elegant retro dancefloor mood.",
    "category": "lightshow",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903378/vinco_eventi_galleria/vinco_eventi_galleria/Service_av_discoball.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903378/vinco_eventi_galleria/vinco_eventi_galleria/Service_av_discoball.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/Service_av_discoball",
    "id": "81ee8f8c-e36a-45ee-860f-ab42343aa160",
    "isFallback": true
  },
  {
    "displayOrder": 20,
    "type": "video",
    "titleIta": "Light Show Beam & Scenografia Architetturale",
    "titleEng": "Beam Light Show & Architectural Scenography",
    "subtitleIta": "Illuminazione architetturale dinamica con teste mobili Beam e accenti floreali.",
    "subtitleEng": "Dynamic architectural lighting with Beam moving heads and floral accents.",
    "category": "lightshow",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903381/vinco_eventi_galleria/vinco_eventi_galleria/service_av_fiori_e_beam.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903381/vinco_eventi_galleria/vinco_eventi_galleria/service_av_fiori_e_beam.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/service_av_fiori_e_beam",
    "id": "b719666e-db39-4cdd-b2bc-746efe955686",
    "isFallback": true
  },
  {
    "displayOrder": 21,
    "type": "video",
    "titleIta": "Male Singer Live Pop & Acoustic",
    "titleEng": "Male Singer Live Pop & Acoustic",
    "subtitleIta": "Interpretazioni emozionanti dei più celebri brani italiani e internazionali.",
    "subtitleEng": "Heartfelt interpretations of classic Italian and global hits.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903385/vinco_eventi_galleria/vinco_eventi_galleria/singer_male_live.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903385/vinco_eventi_galleria/vinco_eventi_galleria/singer_male_live.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/singer_male_live",
    "id": "b9702c5b-bb73-4c3d-8cce-1ec3d09ebb09",
    "isFallback": true
  },
  {
    "displayOrder": 22,
    "type": "video",
    "titleIta": "Acoustic Swing & Manouche Band",
    "titleEng": "Acoustic Swing & Manouche Band",
    "subtitleIta": "Ritmi vintage e allegria contagiosa per l'aperitivo e il welcome drink.",
    "subtitleEng": "Vintage rhythms and infectious joy for appetizers and welcome drinks.",
    "category": "band",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903389/vinco_eventi_galleria/vinco_eventi_galleria/swing_band_acustico.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903389/vinco_eventi_galleria/vinco_eventi_galleria/swing_band_acustico.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/swing_band_acustico",
    "id": "9ddd234a-a2b9-4bfe-9511-e73744a375be",
    "isFallback": true
  },
  {
    "displayOrder": 23,
    "type": "video",
    "titleIta": "Trolling Band Comedy & Music Show",
    "titleEng": "Trolling Band Comedy & Music Show",
    "subtitleIta": "Goliardia, musica e coinvolgimento itinerante tra i tavoli.",
    "subtitleEng": "Playful comedy and roaming live music among the wedding tables.",
    "category": "band",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903393/vinco_eventi_galleria/vinco_eventi_galleria/trolling_band_2.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903393/vinco_eventi_galleria/vinco_eventi_galleria/trolling_band_2.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/trolling_band_2",
    "id": "45ef3c30-a91b-4da6-baba-3762bd98f353",
    "isFallback": true
  },
  {
    "displayOrder": 24,
    "type": "video",
    "titleIta": "Trolling Band Dinner Entertainment",
    "titleEng": "Trolling Band Dinner Entertainment",
    "subtitleIta": "Momenti di allegria e risate che uniscono tutti gli invitati a cena.",
    "subtitleEng": "Moments of joy and laughter connecting all guests during dinner.",
    "category": "band",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903396/vinco_eventi_galleria/vinco_eventi_galleria/Trolling_band_dinner.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903396/vinco_eventi_galleria/vinco_eventi_galleria/Trolling_band_dinner.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/Trolling_band_dinner",
    "id": "815fd193-d60a-4b66-8a12-b2e8d15ff939",
    "isFallback": true
  },
  {
    "displayOrder": 25,
    "type": "video",
    "titleIta": "Vintage Rock'n'Roll & Swing Live",
    "titleEng": "Vintage Rock'n'Roll & Swing Live",
    "subtitleIta": "Spettacolo live anni '50 e '60 con look a tema e grandissima grinta.",
    "subtitleEng": "'50s and '60s themed live show packed with style and raw energy.",
    "category": "band",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903400/vinco_eventi_galleria/vinco_eventi_galleria/vintage_band.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903400/vinco_eventi_galleria/vinco_eventi_galleria/vintage_band.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/vintage_band",
    "id": "f712cff4-af47-4bb7-a891-744c35b7ea86",
    "isFallback": true
  },
  {
    "displayOrder": 26,
    "type": "video",
    "titleIta": "Electric Violin & LED Sax Duet",
    "titleEng": "Electric Violin & LED Sax Duet",
    "subtitleIta": "Il dinamico connubio tra violino elettrico e sax luminoso per il taglio torta.",
    "subtitleEng": "Dynamic fusion of electric violin and LED sax for cake cutting & party.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/video/upload/v1787903404/vinco_eventi_galleria/vinco_eventi_galleria/violino___sax.mp4",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/video/upload/f_jpg,q_auto,w_720,so_2/v1787903404/vinco_eventi_galleria/vinco_eventi_galleria/violino___sax.jpg",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/violino___sax",
    "id": "3826e38f-a075-407a-a221-f07e2f60267a",
    "isFallback": true
  },
  {
    "displayOrder": 27,
    "type": "image",
    "titleIta": "Trio Femminile Arpa, Violino e Clarinetto",
    "titleEng": "All-Female Trio: Harp, Violin & Clarinet",
    "subtitleIta": "Armonie raffinate per cerimonie esclusive e aperitivi di classe.",
    "subtitleEng": "Refined harmonies for luxury wedding ceremonies and classy cocktail hours.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903406/vinco_eventi_galleria/vinco_eventi_galleria/Arpa_violino_e_clarinetto_women.webp",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903406/vinco_eventi_galleria/vinco_eventi_galleria/Arpa_violino_e_clarinetto_women.webp",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/Arpa_violino_e_clarinetto_women",
    "id": "dc7dffef-fa71-4ef9-9078-87fc90e26d35",
    "isFallback": true
  },
  {
    "displayOrder": 28,
    "type": "image",
    "titleIta": "Live Band Lineup Completo",
    "titleEng": "Full Live Band Lineup",
    "subtitleIta": "Formazione completa di musicisti professionisti pronti ad accendere la serata.",
    "subtitleEng": "Complete lineup of seasoned musicians ready to ignite the dancefloor.",
    "category": "band",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903407/vinco_eventi_galleria/vinco_eventi_galleria/Band.webp",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903407/vinco_eventi_galleria/vinco_eventi_galleria/Band.webp",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/Band",
    "id": "ecf4586f-dc78-4dfe-a831-e58e946a0b4a",
    "isFallback": true
  },
  {
    "displayOrder": 29,
    "type": "image",
    "titleIta": "DJ Set Private Exclusive Event",
    "titleEng": "DJ Set Private Exclusive Event",
    "subtitleIta": "Regia musicale e luci personalizzate per feste private di prestigio.",
    "subtitleEng": "Tailored soundtrack and lighting design for high-end private parties.",
    "category": "djset",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903408/vinco_eventi_galleria/vinco_eventi_galleria/foto_dj_enzo_evento_privato.webp",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903408/vinco_eventi_galleria/vinco_eventi_galleria/foto_dj_enzo_evento_privato.webp",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/foto_dj_enzo_evento_privato",
    "id": "f684a54a-3a3e-4f35-b893-dd1d02d273e5",
    "isFallback": true
  },
  {
    "displayOrder": 30,
    "type": "image",
    "titleIta": "Summer Sunset & Pool Party DJ Set",
    "titleEng": "Summer Sunset & Pool Party DJ Set",
    "subtitleIta": "Vibes estive, house raffinata e atmosfera rilassata a bordo piscina.",
    "subtitleEng": "Summer vibes, refined deep house and poolside sunset ambience.",
    "category": "djset",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903410/vinco_eventi_galleria/vinco_eventi_galleria/foto_dj_enzo_pool_party.webp",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903410/vinco_eventi_galleria/vinco_eventi_galleria/foto_dj_enzo_pool_party.webp",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/foto_dj_enzo_pool_party",
    "id": "4267f8f1-8aec-4ed4-9b15-f8111bc063e0",
    "isFallback": true
  },
  {
    "displayOrder": 31,
    "type": "image",
    "titleIta": "Live Band on Stage Performance",
    "titleEng": "Live Band on Stage Performance",
    "subtitleIta": "Impatto scenico e qualità audio per i palchi più prestigiosi.",
    "subtitleEng": "Stage presence and pristine sound for premier wedding venues.",
    "category": "band",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903411/vinco_eventi_galleria/vinco_eventi_galleria/live_band.webp",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903411/vinco_eventi_galleria/vinco_eventi_galleria/live_band.webp",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/live_band",
    "id": "1e48449d-0c8d-41ad-b3fa-6e5c98c9fef4",
    "isFallback": true
  },
  {
    "displayOrder": 32,
    "type": "image",
    "titleIta": "Live Vocals & Stage Entertainment",
    "titleEng": "Live Vocals & Stage Entertainment",
    "subtitleIta": "Presenza scenica magnetica e repertorio vocale di altissimo livello.",
    "subtitleEng": "Magnetic stage presence and top-tier vocal performance.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903412/vinco_eventi_galleria/vinco_eventi_galleria/live_singer_with_show.webp",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903412/vinco_eventi_galleria/vinco_eventi_galleria/live_singer_with_show.webp",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/live_singer_with_show",
    "id": "979fe1a5-7ca1-401c-8a78-ed16de9b9c57",
    "isFallback": true
  },
  {
    "displayOrder": 33,
    "type": "image",
    "titleIta": "Live Percussion Setup & Congas",
    "titleEng": "Live Percussion Setup & Congas",
    "subtitleIta": "Ritmi tribali e sonorità calde per accompagnare il DJ set.",
    "subtitleEng": "Tribal rhythms and acoustic warmth accompanying the live DJ set.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903413/vinco_eventi_galleria/vinco_eventi_galleria/percussioni.webp",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903413/vinco_eventi_galleria/vinco_eventi_galleria/percussioni.webp",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/percussioni",
    "id": "f3de9fe7-48bc-4160-be18-b4369cac6d7e",
    "isFallback": true
  },
  {
    "displayOrder": 34,
    "type": "image",
    "titleIta": "Pizzica Salentina & Tradizione Popolare",
    "titleEng": "Salento Pizzica & Folk Tradition",
    "subtitleIta": "La travolgente energia della tradizione pugliese con tamburelli e danzatori.",
    "subtitleEng": "The infectious pulse of Apulian folk tradition with tambourines and dancers.",
    "category": "band",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903414/vinco_eventi_galleria/vinco_eventi_galleria/pizzica.webp",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903414/vinco_eventi_galleria/vinco_eventi_galleria/pizzica.webp",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/pizzica",
    "id": "a3df4830-82db-4025-8cd3-0d811c730c2c",
    "isFallback": true
  },
  {
    "displayOrder": 35,
    "type": "image",
    "titleIta": "Sax Emotion con gli Sposi",
    "titleEng": "Sax Emotion with the Newlyweds",
    "subtitleIta": "Momenti intimi e coinvolgenti durante il ballo degli sposi.",
    "subtitleEng": "Intimate, unforgettable moments during the couple's first dance.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903416/vinco_eventi_galleria/vinco_eventi_galleria/sax_con_sposi_bn.webp",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903416/vinco_eventi_galleria/vinco_eventi_galleria/sax_con_sposi_bn.webp",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/sax_con_sposi_bn",
    "id": "5f01135e-721a-4035-b815-cc0105d84e51",
    "isFallback": true
  },
  {
    "displayOrder": 36,
    "type": "image",
    "titleIta": "Service Audio Luci & Struttura Palco Frontale",
    "titleEng": "Audio-Visual Stage & Truss Rigging Setup",
    "subtitleIta": "Tecnologie audio-luci all'avanguardia e americane modulari.",
    "subtitleEng": "Cutting-edge AV technology and modular truss lighting architecture.",
    "category": "lightshow",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903418/vinco_eventi_galleria/vinco_eventi_galleria/service_av_palco_frontale.webp",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903418/vinco_eventi_galleria/vinco_eventi_galleria/service_av_palco_frontale.webp",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/service_av_palco_frontale",
    "id": "265708e2-d025-46db-9b91-d7c6d41b9481",
    "isFallback": true
  },
  {
    "displayOrder": 37,
    "type": "image",
    "titleIta": "Street Band Itinerante Festosa",
    "titleEng": "Roaming Itinerant Street Brass Band",
    "subtitleIta": "Fiati, ottoni e percussioni in movimento per un'accoglienza calorosa.",
    "subtitleEng": "Brass and drums roaming among guests for an energetic welcome.",
    "category": "band",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903419/vinco_eventi_galleria/vinco_eventi_galleria/Street_band.webp",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903419/vinco_eventi_galleria/vinco_eventi_galleria/Street_band.webp",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/Street_band",
    "id": "f74ca364-0dbb-4888-8fac-db1d436ca6e8",
    "isFallback": true
  },
  {
    "displayOrder": 38,
    "type": "image",
    "titleIta": "Trio d'Archi Acustico su Palchetti Scenografici",
    "titleEng": "Acoustic String Trio on Scenic Platforms",
    "subtitleIta": "Esecuzione classica e contemporanea in armonia con la location.",
    "subtitleEng": "Classical and modern crossover string execution matching the venue aesthetics.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903420/vinco_eventi_galleria/vinco_eventi_galleria/Trio_archi_su_palchetti.webp",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903420/vinco_eventi_galleria/vinco_eventi_galleria/Trio_archi_su_palchetti.webp",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/Trio_archi_su_palchetti",
    "id": "89fce0bf-1582-40fb-88f7-51f2a8580e72",
    "isFallback": true
  },
  {
    "displayOrder": 39,
    "type": "image",
    "titleIta": "Vintage Swing Band Welcome Drinks",
    "titleEng": "Vintage Swing Band Welcome Drinks",
    "subtitleIta": "Atmosfere d'altri tempi per un cocktail party fresco ed elegante.",
    "subtitleEng": "Retro vibes for a fresh, sophisticated welcome cocktail party.",
    "category": "band",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903422/vinco_eventi_galleria/vinco_eventi_galleria/vintage_band_aperitivo.webp",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903422/vinco_eventi_galleria/vinco_eventi_galleria/vintage_band_aperitivo.webp",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/vintage_band_aperitivo",
    "id": "9fbab14b-b5cf-497e-becc-2b1557a91113",
    "isFallback": true
  },
  {
    "displayOrder": 40,
    "type": "image",
    "titleIta": "Violoncello Soloist & Romantic Mood",
    "titleEng": "Violoncello Soloist & Romantic Mood",
    "subtitleIta": "Profondità timbrica ed emozione pura per il momento del sì.",
    "subtitleEng": "Timbre depth and pure resonance for ceremony emotional highlights.",
    "category": "live",
    "featured": false,
    "startTime": null,
    "src": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903423/vinco_eventi_galleria/vinco_eventi_galleria/violoncello.webp",
    "posterUrl": "https://res.cloudinary.com/fzdamrbc/image/upload/v1787903423/vinco_eventi_galleria/vinco_eventi_galleria/violoncello.webp",
    "publicId": "vinco_eventi_galleria/vinco_eventi_galleria/violoncello",
    "id": "ff109778-7895-4dd1-bc06-d72f8a6d9df3",
    "isFallback": true
  }
];
