// NOTA: Questo file è usato come fallback di emergenza quando il backend non è raggiungibile.
// La fonte primaria dei dati è il DB (PostgreSQL via Spring Boot) con URL Cloudinary.

export const galleryItems = [
  {
    id: "a94264ce-4bdd-47a4-b41b-22120dc471a2",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785861122/vinco_eventi_galleria/rftirtcmqxgjsqsyu6fv.mp4",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739092/vinco_eventi_galleria/srdtwafxbjz3w9hdkxax.jpg",
    titleIta: "Set ELETTRICO - Promo on Fire!",
    titleEng: "ELECTRICAL Set - Promo on Fire!",
    subtitleIta: "La carica travolgente del nostro set elettrico live (minuto 1:00)",
    subtitleEng: "The overwhelming energy of our live electric set (start minute 1:00)",
    category: "djset",
    featured: true,
    startTime: 60,
    displayOrder: 1,
  },
  {
    id: "1bca78ef-e6c6-4285-98e6-9b989c3d91f2",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785739102/vinco_eventi_galleria/wdjpouelk0wgy8b7ayxb.mov",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738823/vinco_eventi_galleria/eo7tqi5jal8lbxvma4bo.jpg",
    titleIta: "Crossroads Live Performance",
    titleEng: "Crossroads Live Performance",
    subtitleIta: "Spettacolo musicale d'impatto e ritmo coinvolgente",
    subtitleEng: "High impact musical performance with engaging rhythm",
    category: "band",
    featured: true,
    startTime: null,
    displayOrder: 2,
  },
  {
    id: "9ea48442-9008-4b27-bc8b-70d31d5c0c44",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785739094/vinco_eventi_galleria/vntlhm89bfzrdh2xgy2p.mov",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739092/vinco_eventi_galleria/srdtwafxbjz3w9hdkxax.jpg",
    titleIta: "DJ Set Exclusive Live",
    titleEng: "DJ Set Exclusive Live",
    subtitleIta: "Carica ed energia per eventi unici",
    subtitleEng: "Energy and passion for unique events",
    category: "djset",
    featured: true,
    startTime: null,
    displayOrder: 3,
  },
  {
    id: "4c740398-3c05-4c07-b35a-43ae87ee287b",
    type: "image",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739092/vinco_eventi_galleria/srdtwafxbjz3w9hdkxax.jpg",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739092/vinco_eventi_galleria/srdtwafxbjz3w9hdkxax.jpg",
    titleIta: "Console DJ Set",
    titleEng: "Console DJ Set",
    subtitleIta: "Musica e regia per la serata",
    subtitleEng: "Music and direction for your evening",
    category: "djset",
    featured: true,
    startTime: null,
    displayOrder: 4,
  },
  {
    id: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785739072/vinco_eventi_galleria/r9e4uokfrbmpwadra7al.mov",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739092/vinco_eventi_galleria/srdtwafxbjz3w9hdkxax.jpg",
    titleIta: "Exclusive Night Party",
    titleEng: "Exclusive Night Party",
    subtitleIta: "Pista piena e grande energia per una serata indimenticabile",
    subtitleEng: "Packed dancefloor and intense energy for an unforgettable night",
    category: "djset",
    featured: true,
    startTime: null,
    displayOrder: 5,
  },
  {
    id: "e6f7a8b9-1234-4567-890a-bcdef1234567",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785739059/vinco_eventi_galleria/ef6cr5xt3l4utt5ngzbz.mp4",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739108/vinco_eventi_galleria/ftaaf6e3ry3wykbvdxdn.webp",
    titleIta: "Live Band Night Performance",
    titleEng: "Live Band Night Performance",
    subtitleIta: "Spettacolo e musica dal vivo",
    subtitleEng: "Live show and music performance",
    category: "band",
    featured: true,
    startTime: null,
    displayOrder: 6,
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    type: "image",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739108/vinco_eventi_galleria/ftaaf6e3ry3wykbvdxdn.webp",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739108/vinco_eventi_galleria/ftaaf6e3ry3wykbvdxdn.webp",
    titleIta: "Esibizione Vocalist & Cantante",
    titleEng: "Vocalist & Singer Performance",
    subtitleIta: "Emozione pura durante il party",
    subtitleEng: "Pure emotion during the party",
    category: "band",
    featured: true,
    startTime: null,
    displayOrder: 7,
  },
  {
    id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785739049/vinco_eventi_galleria/k6nrydw6lhpgaiztomgd.mov",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739047/vinco_eventi_galleria/txbfapyv9ujglspk13eo.jpg",
    titleIta: "Luci LED & Console Show",
    titleEng: "LED Lights & Console Show",
    subtitleIta: "Scenografie luminose e sound system",
    subtitleEng: "Lighting design and sound system",
    category: "lightshow",
    featured: false,
    startTime: null,
    displayOrder: 8,
  },
  {
    id: "c3d4e5f6-a7b8-9012-cdef-123456789012",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785739011/vinco_eventi_galleria/lq4emmoiddqhzpbgthq3.mov",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739092/vinco_eventi_galleria/srdtwafxbjz3w9hdkxax.jpg",
    titleIta: "Live Energy & Dj Set",
    titleEng: "Live Energy & Dj Set",
    subtitleIta: "Intrattenimento e regia musicale sul palco",
    subtitleEng: "Entertainment and musical direction on stage",
    category: "live",
    featured: false,
    startTime: null,
    displayOrder: 9,
  },
  {
    id: "d4e5f6a7-b8c9-0123-def1-234567890123",
    type: "image",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739047/vinco_eventi_galleria/txbfapyv9ujglspk13eo.jpg",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739047/vinco_eventi_galleria/txbfapyv9ujglspk13eo.jpg",
    titleIta: "Illuminazione Cielo Stellato",
    titleEng: "Starry Sky Lighting",
    subtitleIta: "Atmosfera magica per la cena all'aperto",
    subtitleEng: "Magical atmosphere for outdoor dinner",
    category: "decor",
    featured: false,
    startTime: null,
    displayOrder: 10,
  },
  {
    id: "e5f6a7b8-c9d0-1234-ef12-345678901234",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785739001/vinco_eventi_galleria/ufpb1xiseuvs1lsxonad.mp4",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738998/vinco_eventi_galleria/eeaxtuj0fwjqzspt38fd.jpg",
    titleIta: "Wedding Party Highlights",
    titleEng: "Wedding Party Highlights",
    subtitleIta: "I momenti più belli ed emozionanti del party",
    subtitleEng: "The best and most exciting moments of the party",
    category: "wedding",
    featured: false,
    startTime: null,
    displayOrder: 11,
  },
  {
    id: "f6a7b8c9-d0e1-2345-f123-456789012345",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785738970/vinco_eventi_galleria/zhhw5yesgmrwsift9sow.mov",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739092/vinco_eventi_galleria/srdtwafxbjz3w9hdkxax.jpg",
    titleIta: "Party & Clubbing Vibe",
    titleEng: "Party & Clubbing Vibe",
    subtitleIta: "Pista piena e divertimento assicurato",
    subtitleEng: "Full dancefloor and guaranteed fun",
    category: "djset",
    featured: false,
    startTime: null,
    displayOrder: 12,
  },
  {
    id: "a7b8c9d0-e1f2-3456-1234-567890123456",
    type: "image",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738998/vinco_eventi_galleria/eeaxtuj0fwjqzspt38fd.jpg",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738998/vinco_eventi_galleria/eeaxtuj0fwjqzspt38fd.jpg",
    titleIta: "Il Primo Bacio degli Sposi",
    titleEng: "The Bride & Groom First Kiss",
    subtitleIta: "Momento romantico accompagnato dalla musica",
    subtitleEng: "Romantic moment accompanied by music",
    category: "wedding",
    featured: false,
    startTime: null,
    displayOrder: 13,
  },
  {
    id: "b8c9d0e1-f2a3-4567-2345-678901234567",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785738959/vinco_eventi_galleria/afrx0hb5jnevhbudiieo.mp4",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739108/vinco_eventi_galleria/ftaaf6e3ry3wykbvdxdn.webp",
    titleIta: "Live Vibes & Social Reel",
    titleEng: "Live Vibes & Social Reel",
    subtitleIta: "La magia dell'evento vista da vicino",
    subtitleEng: "The magic of the event up close",
    category: "live",
    featured: true,
    startTime: null,
    displayOrder: 14,
  },
  {
    id: "c9d0e1f2-a3b4-5678-3456-789012345678",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785738945/vinco_eventi_galleria/etesqmzgylrapntrtrbf.mov",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738823/vinco_eventi_galleria/eo7tqi5jal8lbxvma4bo.jpg",
    titleIta: "Live Acoustics Aperitivo",
    titleEng: "Live Acoustics Cocktail Hour",
    subtitleIta: "Musica dal vivo elegante durante il cocktail",
    subtitleEng: "Elegant live music during cocktail hour",
    category: "band",
    featured: false,
    startTime: null,
    displayOrder: 15,
  },
  {
    id: "d0e1f2a3-b4c5-6789-4567-890123456789",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785738935/vinco_eventi_galleria/vswvgslfquuykapxnr3d.mp4",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739047/vinco_eventi_galleria/txbfapyv9ujglspk13eo.jpg",
    titleIta: "Atmosphere & Lights",
    titleEng: "Atmosphere & Lights",
    subtitleIta: "Service luci ed effetti per un'atmosfera elegante",
    subtitleEng: "Lighting and effects service for an elegant atmosphere",
    category: "lightshow",
    featured: true,
    startTime: null,
    displayOrder: 16,
  },
  {
    id: "e1f2a3b4-c5d6-7890-5678-901234567890",
    type: "image",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738957/vinco_eventi_galleria/difwya2hiwgfwlsn6tc4.jpg",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738957/vinco_eventi_galleria/difwya2hiwgfwlsn6tc4.jpg",
    titleIta: "Brindisi & Taglio Torta",
    titleEng: "Toast & Cake Cutting",
    subtitleIta: "Il culmine dei festeggiamenti",
    subtitleEng: "The climax of the celebrations",
    category: "wedding",
    featured: false,
    startTime: null,
    displayOrder: 17,
  },
  {
    id: "f2a3b4c5-d6e7-8901-6789-012345678901",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785738913/vinco_eventi_galleria/tuu3jqx5c72wyf9ldhbg.mov",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738910/vinco_eventi_galleria/d34yekgmypunr4au4xwv.jpg",
    titleIta: "Fumogeni & Effetti Scenografici",
    titleEng: "Smoke Effects & Special Effects",
    subtitleIta: "Effetti speciali per ingressi e momenti clou",
    subtitleEng: "Special effects for grand entrances and key moments",
    category: "effects",
    featured: true,
    startTime: null,
    displayOrder: 18,
  },
  {
    id: "a3b4c5d6-e7f8-9012-7890-123456789012",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785738895/vinco_eventi_galleria/owjxvhnylisvs0hiyxar.mp4",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738957/vinco_eventi_galleria/difwya2hiwgfwlsn6tc4.jpg",
    titleIta: "Festeggiamenti in Musica",
    titleEng: "Music Celebrations",
    subtitleIta: "Ritmo e divertimento scatenato per gli invitati",
    subtitleEng: "Rhythm and wild fun for the guests",
    category: "djset",
    featured: false,
    startTime: null,
    displayOrder: 19,
  },
  {
    id: "b4c5d6e7-f8a9-0123-8901-234567890123",
    type: "image",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738910/vinco_eventi_galleria/d34yekgmypunr4au4xwv.jpg",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738910/vinco_eventi_galleria/d34yekgmypunr4au4xwv.jpg",
    titleIta: "Fumogeni Colorati Sposi",
    titleEng: "Colored Smoke Effects",
    subtitleIta: "Esplosione di colori per un ricordo indimenticabile",
    subtitleEng: "Burst of colors for an unforgettable memory",
    category: "effects",
    featured: false,
    startTime: null,
    displayOrder: 20,
  },
  {
    id: "c5d6e7f8-a9b0-1234-9012-345678901234",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785738827/vinco_eventi_galleria/slfbcr7zinspj5coflaa.mov",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739092/vinco_eventi_galleria/srdtwafxbjz3w9hdkxax.jpg",
    titleIta: "DJ Set & Live Mix",
    titleEng: "DJ Set & Live Mix",
    subtitleIta: "Selezione musicale personalizzata",
    subtitleEng: "Customized music selection",
    category: "djset",
    featured: false,
    startTime: null,
    displayOrder: 21,
  },
  {
    id: "d6e7f8a9-b0c1-2345-0123-456789012345",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785738801/vinco_eventi_galleria/so2xar04vohxdsc0lulo.mov",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739092/vinco_eventi_galleria/srdtwafxbjz3w9hdkxax.jpg",
    titleIta: "Live Show Console",
    titleEng: "Live Show Console",
    subtitleIta: "Performance ed energia con la regia di VINCO EVENTI",
    subtitleEng: "Performance and energy directed by VINCO EVENTI",
    category: "djset",
    featured: false,
    startTime: null,
    displayOrder: 22,
  },
  {
    id: "e7f8a9b0-c1d2-3456-1234-567890123456",
    type: "image",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738823/vinco_eventi_galleria/eo7tqi5jal8lbxvma4bo.jpg",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738823/vinco_eventi_galleria/eo7tqi5jal8lbxvma4bo.jpg",
    titleIta: "Band Live Aperitivo",
    titleEng: "Live Band Cocktail Hour",
    subtitleIta: "Ritmi lounge e pop acustico",
    subtitleEng: "Lounge rhythms and acoustic pop",
    category: "band",
    featured: false,
    startTime: null,
    displayOrder: 23,
  },
  {
    id: "f8a9b0c1-d2e3-4567-2345-678901234567",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785738787/vinco_eventi_galleria/uiqet8umjkjq3b4wej1c.mp4",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739092/vinco_eventi_galleria/srdtwafxbjz3w9hdkxax.jpg",
    titleIta: "DJ Set Moment",
    titleEng: "DJ Set Moment",
    subtitleIta: "Sound system e selezione musicale d'eccellenza",
    subtitleEng: "Sound system and music selection of excellence",
    category: "djset",
    featured: false,
    startTime: null,
    displayOrder: 24,
  },
  {
    id: "a9b0c1d2-e3f4-5678-3456-789012345678",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785738745/vinco_eventi_galleria/flg3kduqpo9yoq79fjom.mp4",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739108/vinco_eventi_galleria/ftaaf6e3ry3wykbvdxdn.webp",
    titleIta: "Live Show Finale",
    titleEng: "Live Show Finale",
    subtitleIta: "Gran finale con la band al completo",
    subtitleEng: "Grand finale with full band",
    category: "band",
    featured: false,
    startTime: null,
    displayOrder: 25,
  },
  {
    id: "b0c1d2e3-f4a5-6789-4567-890123456789",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785738686/vinco_eventi_galleria/oiuv1egd7bx5atkiwzbb.mov",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739108/vinco_eventi_galleria/ftaaf6e3ry3wykbvdxdn.webp",
    titleIta: "Show dal Vivo",
    titleEng: "Live Performance Show",
    subtitleIta: "Coinvolgimento e spettacolo per tutti gli ospiti",
    subtitleEng: "Engagement and show for all guests",
    category: "live",
    featured: false,
    startTime: null,
    displayOrder: 26,
  },
  {
    id: "c1d2e3f4-a5b6-7890-5678-901234567890",
    type: "image",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738784/vinco_eventi_galleria/eb0ki9vvv83w4nlhybid.webp",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738784/vinco_eventi_galleria/eb0ki9vvv83w4nlhybid.webp",
    titleIta: "Cocktail & Sax Vibe",
    titleEng: "Cocktail & Sax Vibe",
    subtitleIta: "Eleganza e sonorità moderne",
    subtitleEng: "Elegance and modern sounds",
    category: "band",
    featured: false,
    startTime: null,
    displayOrder: 27,
  },
  {
    id: "d2e3f4a5-b6c7-8901-6789-012345678901",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785738661/vinco_eventi_galleria/uwi6mmwruee6037hbsuo.mp4",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738823/vinco_eventi_galleria/eo7tqi5jal8lbxvma4bo.jpg",
    titleIta: "Live Session Highlight",
    titleEng: "Live Session Highlight",
    subtitleIta: "Un assaggio del nostro intrattenimento dal vivo",
    subtitleEng: "A taste of our live entertainment",
    category: "band",
    featured: false,
    startTime: null,
    displayOrder: 28,
  },
  {
    id: "e3f4a5b6-c7d8-9012-7890-123456789012",
    type: "image",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739100/vinco_eventi_galleria/pdz6t0sfegbelnr12wb3.png",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739100/vinco_eventi_galleria/pdz6t0sfegbelnr12wb3.png",
    titleIta: "I Nostri Musicisti",
    titleEng: "Our Musicians",
    subtitleIta: "Professionisti al servizio del tuo evento",
    subtitleEng: "Professionals at the service of your event",
    category: "band",
    featured: false,
    startTime: null,
    displayOrder: 29,
  },
  {
    id: "f4a5b6c7-d8e9-0123-8901-234567890123",
    type: "video",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/video/upload/v1785738637/vinco_eventi_galleria/jlqctoerysynttow2lpf.mov",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785739100/vinco_eventi_galleria/pdz6t0sfegbelnr12wb3.png",
    titleIta: "Live Sound Experience",
    titleEng: "Live Sound Experience",
    subtitleIta: "Musica e passione al servizio del tuo evento",
    subtitleEng: "Music and passion at the service of your event",
    category: "band",
    featured: false,
    startTime: null,
    displayOrder: 30,
  },
  {
    id: "a5b6c7d8-e9f0-1234-9012-345678901234",
    type: "image",
    isFallback: true,
    src: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738683/vinco_eventi_galleria/xp9vsaeg4vd8o7d2hzne.jpg",
    posterUrl: "https://res.cloudinary.com/ytjdxerb/image/upload/v1785738683/vinco_eventi_galleria/xp9vsaeg4vd8o7d2hzne.jpg",
    titleIta: "Accoglienza Ospiti in Musica",
    titleEng: "Guest Welcome in Music",
    subtitleIta: "L'atmosfera ideale fin dai primi minuti",
    subtitleEng: "The ideal atmosphere from the very first minutes",
    category: "band",
    featured: false,
    startTime: null,
    displayOrder: 31,
  }
];
